server:
  port: 8123

spring:
  datasource:
#    url: jdbc:sqlserver://localhost:1433;DatabaseName=vote
#    username: sa
#    password: boding!@#$1234
#    #使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:mysql://localhost:3306/vote?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql